### ISSUE TITLE
关于6盘开发的两个问题

### ISSUE THREAD

**Issue by PikaByter** [zerorooot/nap6#1]
作者大大你好，我上个月写了一个自动提交离线下载的python程序，但在开发的时候，从官网上获得了[**API文档**](https://github.com/qingzhenyun/qingzhenyun-api-doc/tree/master/zh-CN/v3/15.%E7%BB%9F%E4%B8%80%E8%AE%A4%E8%AF%81)，里面关于登录的三种方法都需要使用浏览器来进行访问，参考这些文档，我采用了驱动模拟浏览器登录后获取**cookie**的方法，来实现登录操作。

这种方法十分低效，后来我试图从网页上找出另外的登录方法，但是失败了，因为我通过查看**network**卡只找到了 **/v3/oauth/login**的**API**，在我模拟这个**post**请求后，我就不知道下一步该做什么了：

![network](https://gitee.com/AndrewYu/pictures/raw/master/img/image_47.png)

今天看到了您的项目，才从您的代码中知道了后续操作应为：**header中添加上一步response头部的"set-cookie"，向check_cookie发get请求，获取response之后，再从response头部的两个"set-cookie"中解析token和签名，就可以组成cookie了**。

**因此，我的问题是，您是如何通过什么工具或方法发现这后续操作的呢？（PS：我拿到的token的过期时间有一个月，应该没有这么久吧，真实的过期时间是多久呢？）**

**最后，谢谢您开源的代码！！**

**Comment by zerorooot** [comment]
通过抓包抓出来的，用web端登一次，找所有有关请求多试几次就行了，算是强行破解了吧。其实我认为比较好的是用浏览器登录，具体形式与代码参考Rn6Pan或者six-cli

 token是使用jwt来验证的，真实过期时间得问官方了。

最后，感谢star(๑Ő௰Ő๑)
