### ISSUE TITLE
要是能自动打开磁力就更好了

### ISSUE THREAD

**Issue by CODYI1** [zerorooot/nap6#2]
如下图那样
![Screenshot_20210329-123306](https://user-images.githubusercontent.com/34393173/112787397-01cd0780-908b-11eb-9fa1-b4e9df2be895.jpg)
点击磁力后能够用6pan打开 并自动粘贴到离线下载框内 那就非常的舒服了

**Comment by zerorooot** [comment]
666，感谢建议，我研究研究

**Comment by zerorooot** [comment]
代码已更新，如果着急的话，可先行编译；我自己先测试测试，如果没问题的话再发布
