### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wnbh** [zerorooot/nap6#3]
希望大佬做个批量下载，一行一个链接，输出至剪切板。

**Comment by zerorooot** [comment]
是选中多个文件/文件夹，然后一行一个链接，输出至剪切板吗？如果是这样的话那可能不好弄ヾ(´A‘)ノﾟ，目前多选下载使用方案是官方的"打包下载"，把多个总和小于3G(具体多少记不清了，大概是这么大)的文件压缩并下载。

我先研究研究，暂时先单独下载将就一下吧(｡•ˇ‸ˇ•｡)

**Comment by wnbh** [comment]
嗯 是这样的 可不可以这样 判断选中的文件 不用一次全部提取 挨个提取最后输出 就相当于是减去了自己再次选择文件点击下载这个步骤

**Comment by zerorooot** [comment]
也就是不打包下载，每个文件分别输出一个链接？如果是这样的话，要分两种情况讨论
1、选中的文件大小总和**小于等于**3g。如果是这种情况，**不支持**每个文件对应一个下载链接，分别输出(当前版本会直接把这几个文件压缩，整体下载)
2、选中的文件大小总和**大于**3g，目前的版本会提示“获取下载链接失败”。如果你说的是这种情况，那确实需要再仔细研究研究了
注：上述讨论的仅是多个**文件**的下载，**不包含文件夹**，文件夹的下载另说，具体参见[这个](https://github.com/Mrs4s/six-cli/issues/15)

**Comment by wnbh** [comment]
嗯 我觉得可以这样 
如果选中的只有文件 让我们自己决定是否打包下载 打包下载还是按现在的逻辑 不打包就一个文件一个链接 然后选择打包下载时提示不能大于3g 选择不打包下载提示链接具有时效之类的 这样可以有效避免想快速提取多个链接而又大于3g的情况 
如果所选当中有文件夹就现在的逻辑就行默认打包下载

**Comment by zerorooot** [comment]
嗯嗯，下次更新加上
